### ISSUE TITLE
erro 404 em muitos itens do menu

### ISSUE THREAD

**Issue by patrickalima98** [CapivaraJS/capivarajs.github.io#10]
Essa página está no menu, porém não está sendo encontrada, veja o link:
https://capivarajs.github.io/#/Directives/cp-style

**Comment by patrickalima98** [comment]
Na verdade, estou navegando pelo site e não consigo usar muitos menus da diretiva, o campo de busca sugere muitos itens ao pesquisar por cli, porém os mesmos não funcionam, retornam erro 404. Além disso esses itens do menu não funcionam:

- Capivara CLI
- Ciclo de Vida
- cp-blur
- cp-class
- cp-click
- cp-dblclick
- cp-disabled
- cp-if
- cp-else-if
- cp-focus
- cp-hide
- cp-init
- cp-mouse
- cp-style

**Comment by mateusmirandaalmeida** [comment]
Olá @patrickalima98 ainda está com esse problema?

**Comment by patrickalima98** [comment]
Olá @mateusmirandaalmeida agora está tudo ok, todos os links funcionando.
